[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialMatrices = "928aab9d-ef52-54ac-8ca1-acd7ca42c160"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
